# Generated by Django 5.0.6 on 2024-06-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='plan_length',
            field=models.IntegerField(choices=[(1, '3 Weeks'), (2, '6 Weeks'), (3, '9 Weeks')], default=1),
        ),
    ]
