# Generated by Django 5.0.6 on 2024-06-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperformance',
            name='content',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
