# Generated by Django 5.0.6 on 2024-06-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performances", "0002_alter_userperformance_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userperformance",
            name="time",
            field=models.TimeField(help_text="Enter time in HH:MM:SS format"),
        ),
    ]
