# Generated by Django 5.0.6 on 2024-06-11 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_level', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1)),
                ('hours_available', models.IntegerField(choices=[(1, '3 Hours'), (2, '6 Hours'), (3, '9 Hours')], default=1)),
                ('weeks_available', models.IntegerField(choices=[(1, '3 Weeks'), (2, '6 Weeks'), (3, '9 Weeks')], default=1)),
                ('content', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('complete', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-plan_level', '-hours_available', '-weeks_available'],
            },
        ),
    ]
