# Generated by Django 5.0.6 on 2024-06-26 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
