# Generated by Django 5.0.6 on 2024-06-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0002_alter_trainingplan_content_alter_trainingplan_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainingplan',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
