# Generated by Django 5.0.6 on 2024-06-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingPlans', '0002_remove_trainingplan_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingplan',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
